apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ecommerce-ingress
  namespace: ecommerce
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-path: /actuator/health
    alb.ingress.kubernetes.io/group.name: agentic-microservices
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /ecommerceApp
            pathType: Prefix
            backend:
              service:
                name: ecommerce-service
                port:
                  number: 8090
          - path: /product-service
            pathType: Prefix
            backend:
              service:
                name: product-service
                port:
                  number: 8090
          - path: /image-service
            pathType: Prefix
            backend:
              service:
                name: images-service
                port:
                  number: 8090
