apiVersion: apps/v1
kind: Deployment
metadata:
  name: observability-server
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: observability-server
  template:
    metadata:
      labels:
        app: observability-server
    spec:
      containers:
        - name: observability-server
          image: observability-server:v1
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: observability-server-config
          ports:
            - containerPort: 8091
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8091
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8091
            initialDelaySeconds: 20
            periodSeconds: 15
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 300m
              memory: 512Mi
