apiVersion: v1
kind: Service
metadata:
  name: observability-agent
  namespace: observability
spec:
  selector:
    app: observability-agent
  ports:
    - protocol: TCP
      port: 8091
      targetPort: 8091
  type: ClusterIP
