apiVersion: apps/v1
kind: Deployment
metadata:
  name: images
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: images
  template:
    metadata:
      labels:
        app: images
    spec:
      containers:
        - name: images
          image: images:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8090
          envFrom:
            - configMapRef:
                name: images-config
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:TieredStopAtLevel=1 -Xms128m -Xmx400m"
          startupProbe:
            httpGet:
              path: /image-service/actuator/health
              port: 8090
            periodSeconds: 5
            failureThreshold: 36
          readinessProbe:
            httpGet:
              path: /image-service/actuator/health
              port: 8090
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /image-service/actuator/health
              port: 8090
            initialDelaySeconds: 180
            periodSeconds: 15
            failureThreshold: 4
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
