apiVersion: v1
kind: ConfigMap
metadata:
  name: product-config
  namespace: ecommerce
data:
  SERVER_PORT: "8090"
  SERVER_SERVLET_CONTEXT_PATH: "/product-service"
  SPRING_H2_CONSOLE_ENABLED: "false"
  SPRING_DATASOURCE_URL: "jdbc:h2:mem:productsdb"
  SPRING_JPA_DATABASE_PLATFORM: "org.hibernate.dialect.H2Dialect"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "none"
  SPRING_SQL_INIT_MODE: "always"
  SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION: "true"
  MANAGEMENT_ENDPOINTS_ENABLED_BY_DEFAULT: "true"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,prometheus"
  MANAGEMENT_ENDPOINTS_WEB_BASE_PATH: "/actuator"
  MANAGEMENT_ENDPOINTS_ACCESS_DEFAULT: "unrestricted"
  MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED: "true"
  MANAGEMENT_ENDPOINT_PROMETHEUS_ACCESS: "unrestricted"
  MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED: "true"
  NAME: "Reading from file"
  MANAGEMENT_HEALTH_LIVENESSSTATE_ENABLED: "true"
  MANAGEMENT_HEALTH_READINESSSTATE_ENABLED: "true"
  MANAGEMENT_HEALTH_PROBES_ENABLED: "true"
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: "always"
