apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      imagePullSecrets:
        - name: dockerhub-registry-secret
      containers:
        - name: product
          image: docker.io/sudhavuppalapati/product:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8090
          envFrom:
            - configMapRef:
                name: product-config
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:TieredStopAtLevel=1 -Xms128m -Xmx400m"
          startupProbe:
            httpGet:
              path: /product-service/actuator/health
              port: 8090
            periodSeconds: 5
            failureThreshold: 36
          readinessProbe:
            httpGet:
              path: /product-service/actuator/health
              port: 8090
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /product-service/actuator/health
              port: 8090
            initialDelaySeconds: 180
            periodSeconds: 15
            failureThreshold: 4
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
