apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: observability
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: ecommerce
        static_configs:
          - targets: ["ecommerce-service.ecommerce.svc.cluster.local:8090"]
        metrics_path: /ecommerce-service/actuator/prometheus
        metric_relabel_configs:
          - source_labels: [__name__, area]
            regex: jvm_memory_(used|max)_bytes;nonheap
            action: drop
          - source_labels: [__name__]
            regex: jvm_memory_used_bytes|jvm_memory_max_bytes|jvm_threads_live_threads|jvm_gc_pause_seconds_count|jvm_gc_pause_seconds_sum|jvm_gc_pause_seconds_max|http_server_requests_seconds_count
            action: keep
      - job_name: product
        static_configs:
          - targets: ["product-service.ecommerce.svc.cluster.local:8090"]
        metrics_path: /product-service/actuator/prometheus
        metric_relabel_configs:
          - source_labels: [__name__, area]
            regex: jvm_memory_(used|max)_bytes;nonheap
            action: drop
          - source_labels: [__name__]
            regex: jvm_memory_used_bytes|jvm_memory_max_bytes|jvm_threads_live_threads|jvm_gc_pause_seconds_count|jvm_gc_pause_seconds_sum|jvm_gc_pause_seconds_max|http_server_requests_seconds_count
            action: keep
      - job_name: images
        static_configs:
          - targets: ["images-service.ecommerce.svc.cluster.local:8090"]
        metrics_path: /image-service/actuator/prometheus
        metric_relabel_configs:
          - source_labels: [__name__, area]
            regex: jvm_memory_(used|max)_bytes;nonheap
            action: drop
          - source_labels: [__name__]
            regex: jvm_memory_used_bytes|jvm_memory_max_bytes|jvm_threads_live_threads|jvm_gc_pause_seconds_count|jvm_gc_pause_seconds_sum|jvm_gc_pause_seconds_max|http_server_requests_seconds_count
            action: keep
